on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    container: hajare/rpa-xvfb:alpine

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install robotframework-pabot
          pip install -r requirements.txt
      - name: Run RobotFramework tests
        run: |
          pabot --outputdir results/ tests/
      - name: Get report
        uses: actions/upload-artifact@v3
        with:
          name: report file
          path: results/report.html
      - name: Get log
        uses: actions/upload-artifact@v3
        with:
          name: log file
          path: results/log.html
        
